dataset:
  repo_id: nvidia/LIBERO_LeRobot_v3
  root: /home/yjc1989/ML/robot-learning-project1/data/nvidia_libero_v3/libero_goal

  # Paste the episode IDs produced by inspect_act_training_subset.py
  episodes:
    - 0
    - 43
    - 47
    - 52
    - 54
    - 68
    - 69
    - 72
    - 80
    - 87
    - 102
    - 104
    - 109
    - 128
    - 132
    - 134
    - 143
    - 153
    - 158
    - 170
    - 172
    - 184
    - 189
    - 203
    - 228
    - 236
    - 241
    - 242
    - 247
    - 255
    - 260
    - 263
    - 267
    - 274
    - 276
    - 291
    - 300
    - 329
    - 337
    - 339
    - 347
    - 348
    - 370
    - 371
    - 389
    - 391
    - 422
    - 424
    - 427

  video_backend: pyav
  return_uint8: true
  eval_split: 0.0


policy:
  type: diffusion
  device: cuda
  push_to_hub: false
  
  input_features:
    observation.images.image:
      type: VISUAL
      shape: [3, 256, 256]

    observation.images.wrist_image:
      type: VISUAL
      shape: [3, 256, 256]

    observation.state:
      type: STATE
      shape: [8]

  # Temporal configuration
  n_obs_steps: 2
  horizon: 64
  n_action_steps: 10

  # Vision
  vision_backbone: resnet18
  pretrained_backbone_weights: ResNet18_Weights.IMAGENET1K_V1
  use_separate_rgb_encoder_per_camera: true

  # Diffusion U-Net
  down_dims: [512, 1024, 2048]
  gradient_checkpointing: false

  # Diffusion process
  noise_scheduler_type: DDPM
  num_train_timesteps: 100
  num_inference_steps: null
  prediction_type: epsilon
  clip_sample: true
  clip_sample_range: 1.0

  # Optimization
  optimizer_lr: 1.0e-4
  optimizer_weight_decay: 1.0e-6
  scheduler_name: cosine
  scheduler_warmup_steps: 500


# Reproducibility
seed: 1000
cudnn_deterministic: false


# DataLoader
batch_size: 8
num_workers: 2


# Training
steps: 100

log_freq: 10

save_checkpoint: true
save_freq: 100

# We will perform our own closed-loop evaluation
env_eval_freq: 0
eval_steps: 0


# GPU
accelerator:
  mixed_precision: bf16

  gradient_accumulation:
    steps: 1


# Output
output_dir: /home/yjc1989/ML/robot-learning-project1/results/diffusion_smoke2
job_name: diffusion_bowl_plate_smoke


wandb:
  enable: false
